---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
  - "src/**.less"
exclude_paths: []
